# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies API
      run: dotnet restore ./RentalCar.Manufacturer.API/RentalCar.Manufacturer.API.csproj

    - name: Restore dependencies Unit Tests
      run: dotnet restore ./RentalCar.Manufacturer.UnitTest/RentalCar.Manufacturer.UnitTest.csproj
      
    - name: Build API
      run: dotnet build ./RentalCar.Manufacturer.API/RentalCar.Manufacturer.API.csproj --no-restore

    - name: Build Unit Tests
      run: dotnet build ./RentalCar.Manufacturer.API/RentalCar.Manufacturer.API.csproj --no-restore
      
    - name: Test
      run: dotnet test ./RentalCar.Manufacturer.API/RentalCar.Manufacturer.API.csproj --no-build --verbosity normal
